version: "3.8"

services:
  server-app:
    build: .

    ports:
      - "8080:8080"

    env_file:
      - .env

    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             yarn start"
